
<div class="sidenav">
    <ul class="submenu menu vertical">
      <li><a href="<?= App::config('url') ?>" class="homepage"><?= App::config('naslovApp')?></a></li>

        <li><a href="<?= App::config('url') ?>jelo/index">Unos jela</a></li>
        <li><a href="<?= App::config('url') ?>pice/index">Unos pića</a></li>
        <li><a href="<?= App::config('url') ?>narudzbe/index">Narudžbe</a></li>


        