<div class="card single-accordion">
						    <div class="card-header" id="headingTwo">
						      <h5 class="mb-0">
						          PODACI ZA DOSTAVU
                                <div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>		
                                    <th class="product-name">IME I PREZIME</th>
									<th class="product-price">ADRESA</th>
                                    <th class="telefon">KONTAKT BROJ</th>
									
								</tr>
							</thead>
							<tbody>
								<tr class="table-body-row">
                                    <TD></TD>
									<td class="product-name">MARIJA</td>
									<td class="product-price">BA</td>
                                    <td class="telefon">540654654065465</td>
									
								</tr>
								
							</tbody>
						</table>
					</div>
				</div>
						      </h5>
                               </div>
	<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>NARUDŽBA</p>
						</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>		
                                    <th class="product-name">NAZIV</th>
									<th class="product-price">CIJENA</th>
									<th class="product-quantity">KOLIČINA</th>
									<th class="product-total">UKUPNO</th>
								</tr>
							</thead>
							<tbody>
								<tr class="table-body-row">
                                    <TD></TD>
									<td class="product-name">Strawberry</td>
									<td class="product-price">$85</td>
									<td class="product-quantity"></td>
									<td class="product-total">1</td>
								</tr>
								
							</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>UKUPNO</th>
									<th>CIJENA</th>
								</tr>
							</thead>
							<tbody>
															
								<tr class="total-data">
									<td><strong>UKUPNO: </strong></td>
									<td>$545</td>
								</tr>
							</tbody>
						</table>
</div>

					
				</div>
			</div>
		</div>
	</div>
						
                			 

<div class="container-fluid">
    <form id="status-update-form">
        <input type="hidden" name="id" value="<?php echo $_GET['oid'] ?>">
        <div class="form-group">
            <label for="" class="control-label">Status narudžbe</label>
            <select name="status" id="" class="custom-select custol-select-sm">
                <option value="0" <?php echo $_GET['status'] == 0 ? "selected" : '' ?>>Zaprimljeno</option>
                <option value="1" <?php echo $_GET['status'] == 1 ? "selected" : '' ?>>U izradi</option>
                <option value="2" <?php echo $_GET['status'] == 2 ? "selected" : '' ?>>U dostavi</option>
                <option value="5" <?php echo $_GET['status'] == 3 ? "selected" : '' ?>>Dostavljeno</option>                                       
                </select>
        </div>
    </form>
</div>
<script>
    $(function(){
        $('#status-update-form').submit(function(e){
            e.preventDefault();
            start_loader()
            $.ajax({
                url:_base_url_+"classes/Master.php?f=update_order_status",
                method:"POST",
                data:$(this).serialize(),
                dataType:"json",
                error:err=>{
                    console.log(err)
                    alert_toast("An error occured","error")
                    end_loader()
                },
                success:function(resp){
                    if(!!resp.status && resp.status =='success'){
                        location.reload()
                    }else{
                        console.log(resp)
                        alert_toast("An error occured","error")
                        end_loader()
                    }
                }
            })
        })
    })
</script>