
<table class="dashboard-table">
  <colgroup>
    <col width="150">
    <col width="80">
    <col width="200">
    <col width="60">
    <col width="220">
    <col width="170">
  </colgroup>
  <thead>
    <tr>
		<th>IME I PREZIME</th>
		<th> ADRESA </th>
		<th> NAZIV</th>
		<th> CIJENA </th>
		<th> KOLIČINA </th>
  	</tr>
  		</thead>
  		<tbody>
      <?php foreach($narudzbe as $n): ?>
    	<tr>
      		<td>
       			 <div class="flex-container align-justify align-top">
         			 <div class="flex-child-shrink">
          </div>
          <div class="flex-child-grow">
            <h6 class="dashboard-table-text"><h3><?=$n->kupac?></h3></h6>
          </div>
        </div>
      </td>
      <td><p><?=$n->adresa?></p></td>
      <td><h6><?=$n->ukupno?></h6></td>
      <td>
			<div class="flex-container align-top">
			<div class="flex-child-shrink">
				
			</div>
			<div class="flex-child">
				<h6 class="dashboard-table-text"><h6><?=$n->kolicina?></h6></h6>
			</div>
			</div>
     	 </td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
