<div class="grid-x grid-padding-x" style="text-align: center">
<div class="product-card">
<div class="large-4 cell">
  <div class="product-card-thumbnail">
    <h2 class="product-card-title"><a href="#">Pizza</a></h2>
  <span class="product-card-desc">Product Description</span></br>
  <span class="product-card-price">20 KN</span>
  <div class="product-card-colors">
    <a class="button" href="#">U KOŠARICU</a>    
  </div>
</div>
</div>
</div>

<div class="product-card">
<div class="large-6 cell">
  <div class="product-card-thumbnail">
    <h2 class="product-card-title"><a href="#">Pizza</a></h2>
  <span class="product-card-desc">Product Description</span></br>
  <span class="product-card-price">20 KN</span>
  <div class="product-card-colors">
    <a class="button" href="#">U KOŠARICU</a>    
  </div>
</div>
</div>
</div>

<div class="product-card">
<div class="large-6 cell">
  <div class="product-card-thumbnail">
    <h2 class="product-card-title"><a href="#">Pizza</a></h2>
  <span class="product-card-desc">Product Description</span></br>
  <span class="product-card-price">20 KN</span>
  <div class="product-card-colors">
    <a class="button" href="#">U KOŠARICU</a>    
  </div>
</div>
</div>
</div>

<div class="product-card">
<div class="large-6 cell">
  <div class="product-card-thumbnail">
    <h2 class="product-card-title"><a href="#">Pizza</a></h2>
  <span class="product-card-desc">Product Description</span></br>
  <span class="product-card-price">20 KN</span>
  <div class="product-card-colors">
    <a class="button" href="#">U KOŠARICU</a>    
  </div>
</div>
</div>
</div>

<div class="product-card">
<div class="large-6 cell">
  <div class="product-card-thumbnail">
    <h2 class="product-card-title"><a href="#">Pizza</a></h2>
  <span class="product-card-desc">Product Description</span></br>
  <span class="product-card-price">20 KN</span>
  <div class="product-card-colors">
    <a class="button" href="#">U KOŠARICU</a>    
  </div>
</div>
</div>

