<div class="text-center">
    <h1 class="text-center bg-primary text-white mt-3 p-2"> Welcome to Pizzeria </h1>

    <h6 class="mt-3"> Pick some of our products and never get hungry! </h6>

    <ul class="nav flex-column">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="product/availableProducts?id=1"> Pizza </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=2"> Barbecue </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=3"> Drink </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="product/availableProducts?id=4"> Salad </a>
        </li>
    </ul>
</div>

