<div class="grid-x grid-padding-x" style="text-align: center">
  <div class="ecommerce-header show-for-large">
        <div class="row align-justify align-middle">
            <div class="shrink column">
             <ul class="vertical medium-horizontal menu">
             <li class="main-nav-link"><a href="categories.html">Category 1</a></li>
              <li class="main-nav-link"><a href="#">Category 2</a></li>
              <li class="main-nav-link"><a href="why.html">Category 3</a></li>
              <li class="main-nav-link"><a href="build.html">Category 4</a></li>
              <li class="main-nav-link"><a href="#">Category 5</a></li>
             </ul>
            </div>
        </div>
      </div>
</div>
<div clas="grid-x grid-padding-x" style="text-align: center">
<div class="large-4 cell">
<div class="product-card">
         <div class="product-card-thumbnail">
         <h2 class="product-card-title">Pizza</h2>
         <span class="product-card-desc">Product Description</span></br>
         <span class="product-card-price">20 KN</span>
         <div class="product-card-colors">
         <a class="button" href="#">U KOŠARICU</a>    
        </div>
        </div>
        <div class="product-card">
         <div class="product-card-thumbnail">
         <h2 class="product-card-title">Pizza</h2>
         <span class="product-card-desc">Product Description</span></br>
         <span class="product-card-price">20 KN</span>
         <div class="product-card-colors">
         <a class="button" href="#">U KOŠARICU</a>    
        </div>
        </div>
        <div class="product-card">
         <div class="product-card-thumbnail">
         <h2 class="product-card-title">Pizza</h2>
         <span class="product-card-desc">Product Description</span></br>
         <span class="product-card-price">20 KN</span>
         <div class="product-card-colors">
         <a class="button" href="#">U KOŠARICU</a>    
        </div>
        </div>

</div>
</div>
