<div class="grid-x grid-padding-x" style="text-align: center">
<div class="medium-4 medium-expand">
       <ul class="dropdown menu" data-dropdown-menu>
             <li><a href="<?=App::config('url')?>pizza/">PIZZE</a></li>
             <li><a href="<?=App::config('url')?>plata/">ROŠTILJ</a></li>
              <li><a href="<?=App::config('url')?>tekuci/">PIĆA</a></li>
             <li><a href="<?=App::config('url')?>salata/index">SALATE</a></li>
        </ul>
    </div>
</div>
<br/>
<div class="grid-x grid-padding-x" style="text-align: center">
        <div class="large-6 cell">
    <img src="<?=App::config('url')?>public/img/zid.webp" alt="Pizzeria">
    </div>
    <div class="large-6 cell">
    <img src="<?=App::config('url')?>public/img/slike.webp" alt="Pizzeria">
    </div>
</div>
