<form class="log-in-form"
action="<?=App::config('url')?>login/autoriziraj"
method="POST">
  <h4 class="text-center">Autorizacija</h4>
  <label>Email
    <input type="email" name="email" placeholder="admin@edunova.hr"
    value="<?=$email?>" />
  </label>
  <label>Lozinka
    <input type="password" name="lozinka" placeholder="a"/>
  </label>
  <p>
    <input type="submit" class="button expanded" value="Prijava" />
  </p>
  <?=$poruka?>
</form>


