<form class="log-in-form"
action="<?=App::config('url')?>login/autoriziraj"
method="POST">
  <h4 class="text-center">Autorizacija</h4>
  <label>Email
    <input type="email" name="email" placeholder="admin@mamik-dj.shop"
    value="<?=$email?>" />
  </label>
  <label>Lozinka
    <input type="password" name="lozinka" placeholder="a"/>
  </label>
  <p>
    <input type="submit" class="button expanded" value="Prijava" />
  </p>
  <div class="col">
  <a href="<?=App::config('url')?>registracija" class="btn btn-light btn-block">Nemate račun? Registriraj se</a>
  </div>
  <?=$poruka?>
</form>


