<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Cart
    </span>
</h3>

<div class="col-md-5" style="margin: auto">
    <h4>
        Total items
        <span class="badge bg-primary rounded-pill">
            1
        </span>
    </h4>
    <ul class="list-group mb-3">
        <li class="list-group-item d-flex justify-content-between lh-sm">
            <div>
                <h6 class="my-0">
                    Product name
                </h6>
                <small class="text-muted">
                    Brief description
                </small>
            </div>
            <span class="text-muted">
                12 kn
            </span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
            <span>
                Total price [kn]
            </span>
            <strong>12 kn</strong>
        </li>
    </ul>

    <div class="text-center">
        <a class="btn btn-success" href="#">
            Finish order
        </a>
    </div>
</div>