<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div class="top-bar" id="example-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text"><?=App::config('naslovApp')?></li>
      <li><a href="<?=App::config('url')?>">Početna</a></li>
      <?php if(App::autoriziran()):?>
        <li><a href="<?=App::config('url')?>nadzornaPloca/index">Nadzorna ploča</a></li>
      <?php endif;?>
      </ul>
  </div>
      
      <?php if(App::autoriziran()):?>
        
        <li><a href="#">UNOS</a>
           <ul class="menu">
            <li><a href="<?=App::config('url')?>jelo/index">JELA</a></li>
            <li><a href="<?=App::config('url')?>pice/index">PIĆE</a></li>            
          </ul>
        </li>
      <?php endif;?>
      </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
        <?php if(App::autoriziran()):?>
          <a href="<?=App::config('url')?>login/odjava">Odjavi <?php echo $_SESSION['autoriziran']->ime ?></a>
        <?php else:?>
          <a href="<?=App::config('url')?>login/index">Login</a>
        <?php endif;?>
      </li>
    </ul>
  </div>
</div>