<div class="top-bar" id="example-menu">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <a href="<?= App::config('url') ?>">
                <strong>
                    <?= App::config('naslovApp') ?>
                </strong>
            </a>
            <?php if (App::autoriziran()): ?>
                <li>
                    <a href="<?= App::config('url') ?>Nadzornaploca/index">
                        Nadzorna ploča
                    </a>
                </li>
            <?php endif; ?>
        </ul>
    </div>

    <ul class="menu">
        <li>
            <?php if (App::autoriziran()): ?>
            <a href="<?= App::config('url') ?>login/odjava">
                Odjavi <?php echo $_SESSION['autoriziran']->ime ?>
            </a>
        </li>
        <li>
            <a href="<?= App::config('url') ?>kosarica">
                <i style="color: black;" title="košarica"
                   class="fas fa-1x fa-shopping-cart">
                </i>
                Košarica
            </a>
        </li>
        <li>
            <a href="<?= App::config('url') ?>profil">
                <i style="color: black;" title="profil"
                   class="fas fa-id-card"></i>
                Profil
            </a>
        </li>
        <?php else: ?>
            <li>
                <a href="<?= App::config('url') ?>registracija/index">
                    Registracija
                </a>
            </li>
            <li>
                <a href="<?= App::config('url') ?>login/index">
                    Prijava
                </a>
            </li>
        <?php endif; ?>
    </ul>
</div>
