<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2805.720742059432!2d18.411065215066422!3d45.31406645147058!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475c559a0ed9667f%3A0x547c4906f659deed!2sPizzeria%20Slavonija!5e0!3m2!1shr!2shr!4v1648321652319!5m2!1shr!2shr" width="1350" height="200" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe></p>
</body>
</html>
<hr <?php 
if(App::config('dev')){
    echo 'style="border: 1px solid red;"';
}

?> 
<?php 

if(App::config('dev')){
    echo '<span style="color:blue">MALAS</span> ';
}

echo App::config('naslovApp')?> &copy; 2022