<div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">MOJE NARUDŽBE</h1>
    </div>
    <table>
    <thead>
        <tr>
            <th>Datum</th>
            <th>Proizvodi</th>
            <th>Adresa</th>
            <th>Ukupno</th>            
        </tr>
    </thead>
    <tbody>
        <?php foreach($narudzbe as $narudzba): ?>
            <tr>
                <td><?=$narudzba->datum?></td>
                <td><?=$narudzba->proizvodi?></td>
                <td><?=$narudzba->adresa?></td>
                <td><?=$narudzba->ukupno?></td>               
              </tr>
        <?php endforeach; ?>
    </tbody>
</table>