<form action="<?= App::config('url') ?>proizvod/dodajNovi" method="post">

    <fieldset>
        <legend>Dodavanje novog proizvoda</legend>

        <label for="naziv">Naziv</label>
        <input type="text" name="naziv" value="<?= $proizvod->naziv ?>"/>

        <label for="sastav">Sastav</label>
        <input type="text" name="sastav" value="<?= $proizvod->sastav ?>"/>

        <label for="cijena">Cijena</label>
        <input type="text" name="cijena" id="cijena" value="<?= $proizvod->cijena ?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a class="alert button expanded"
                   href="<?= App::config('url') ?>proizvod/index">
                    Odustani
                </a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi">
            </div>
        </div>
        <?= $poruka ?>
    </fieldset>
</form>