<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        User order history list
    </span>
</h3>

<div class="text-center">
    <?php if(count($orders) === 0): ?>
            <h6 class="text-danger">
                There are no items in history list. Order something and get back here!
            </h6>
    <?php else: ?>
        <table class="table">
            <thead>
            <tr>
                <th> Id </th>
                <th> Product </th>
                <th> Address </th>
                <th> Price </th>
                <th> Status </th>
                <th> Date </th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($orders as $order): ?>
                <tr>
                    <td> <?= $order->order_product_id ?>  </td>
                    <td> <?= $order->product_name ?> </td>
                    <td> <?= $order->order_address ?> </td>
                    <td> <?= $totalPrice ?> </td>
                    <td
                        <?php if($status->order_status === 'Received'): ?>
                            style="color: red;"
                        <?php elseif($status->order_status === 'Preparation'): ?>
                            style="color: cornflowerblue;"
                        <?php else: ?>
                            style="color: greenyellow;"
                        <?php endif; ?>>
                        <strong>
                            <?= $status->order_status ?>
                        </strong>
                    </td>
                    <td> <?= $order->order_date ?> </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>
