<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        User
        <strong>
            <?= $user->name ?> <?= $user->surname ?>
        </strong>
    </span>
</h3>

<div class="m-auto mt-3" style="width: 30%;" >
    <form action="/user/update" method="POST">
        <div class="row">
            <div class="col-6 mb-3">
                <label for="name" class="form-label"> Name </label>
                <input type="text" name="name" class="form-control"
                       id="name" value="<?= $user->name ?>" required>
            </div>

            <div class="col-6 mb-3">
                <label for="surname" class="form-label"> Surname </label>
                <input type="text" name="surname" class="form-control"
                       id="surname" value="<?= $user->surname ?>" required>
            </div>

            <div class="col-6 mb-3">
                <label for="address" class="form-label"> Address </label>
                <input type="text" name="address" class="form-control"
                       id="address" value="<?= $user->address ?>" required>
            </div>

            <div class="col-6 mb-3">
                <label for="telephone" class="form-label"> Telephone </label>
                <input type="tel" name="telephone" class="form-control"
                       id="telephone" value="<?= $user->telephone ?>" required>
            </div>
        </div>

        <div class="text-center mt-3">
            <button type="submit" name="submit_update" class="btn btn-primary"> Update </button>
        </div>
    </form>
</div>