<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Admin dashboard
    </span>
</h3>

<div class="text-center mt-3">
    <ul class="nav flex-column">
        <li>
            <a href="product/" class="btn btn-success text-white">
                Products
            </a>
        </li>
        <li class="mt-2">
            <a href="order/" class="btn btn-success text-white">
                Orders
            </a>
        </li>
    </ul>
</div>
