<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarToggler"
            aria-controls="navbarToggler"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/"> Pizzeria </a>
    <div class="collapse navbar-collapse" id="navbarToggler">
        <?php use Core\App; ?>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <?php if (App::isAuthorized()): ?>
                <?php if (App::isAdmin()): ?>
                    <li class="nav-item">
                        <a class="nav-link" href="/dashboard"> Dashboard </a>
                    </li>
                <?php endif ?>
                <li class="nav-item">
                    <a class="nav-link" href="/user"> Profile </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/user/history"> History </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/order/cart"> Cart </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="user/logout"> Logout </a>
                </li>
            <?php else: ?>
                <li class="nav-item">
                    <a class="nav-link" href="user/login"> Login </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/register"> Register </a>
                </li>
            <?php endif; ?>
            <div class="ms-5"></div>
        </ul>
    </div>
</nav>


