<form action="<?=App::config('url')?>pice/dodajNovi" method="post">

    <fieldset>
        <legend>Dodavanje novog pića</legend>


        <label for="naziv"> Naziv </label>
        <input type="text" name="naziv" value="<?=$pice->naziv?>" />
        

        <lebel for="cijena">Cijena</label>
        <input type="text" name="cijena" id="cijena" value="<?=$pice->cijena?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>pice/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>