<div class="grid-x">
    <div class="cell large-6">
        <h1 style="font-size: 1.5rem;">JELA</h1>
    </div>
    
    <div class="cell large-6" style="text-align: right;">
        <a href="<?=App::config('url')?>jelo/novi">
            <i style="color: green;" title="Dodaj novi" 
                class="fas fa-2x fa-plus-circle"></i>
        </a>
    </div>
</div>

<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Sastav</th>
            <th>Cijena</th>
            <th>Akcija</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach($jela as $jelo): ?>
            <tr>
                <td><?=$jelo->naziv?></td>
                <td><?=$jelo->sastav?></td>
                <td><?=$jelo->cijena?></td>
                 <td></td>
                 <td>
                        <a href="<?=App::config('url')?>jelo/promjena/<?=$jelo->sifra?>">
                            <i title="Promjeni &quot;<?=$jelo->naziv?>&quot;" 
                            class="fas fa-2x fa-edit"></i>
                        </a> 
                        <a onclick="return confirm('Sigurno obrisati <?=$jelo->naziv?>?');" style="margin-left: 20px;" href="<?=App::config('url')?>jelo/brisanje/<?=$jelo->sifra?>">
                            <i style="color: red" title="Obriši <?=$jelo->naziv?>" 
                            class="fas fa-2x fa-trash"></i>
                        </a>  
                
                    </td>  
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

