
<table>
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Sastav</th>
            <th>Cijena</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($jela as $jelo): ?>
            <tr>
                <td><?=$jelo->naziv?></td>
                <td><?=$jelo->sastav?></td>
                <td><?=$jelo->cijena?></td>
                 <td></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>


<!-- Korištenje liste  