<form action="<?=App::config('url')?>jelo/novi" method="post">

    <fieldset>
        <legend>Dodavanje novog jela</legend>


        <label>
            Naziv
            <input type="text" name="naziv" value="<?=$jelo->naziv?>" />
        </label>

        <label>
            Sastav
            <input type="text" name="sastav" value="<?=$jelo->sastav?>" />
        </label>

        <label>
            <label for="cijena">Cijena</label>
        <input type="text" name="cijena" id="cijena" value="<?=$jelo->cijena?>">

        <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" 
                href="<?=App::config('url')?>jelo/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>