<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Register
    </span>
</h3>

<?php if (isset($_SESSION['error_message'])): ?>
    <h6 class="text-center mt-3">
        Error message:
        <span class="text-danger">
            <?php
            echo $_SESSION['error_message'];
            session_unset();
            ?>
        </span>
    </h6>
<?php endif; ?>

<div class="m-auto" style="width: 30%;" >
    <form action="/register/create" method="POST">
        <div class="row">
            <div class="col-6 mb-3">
                <label for="name" class="form-label"> Name </label>
                <input type="text" name="name" class="form-control" id="name" required>
            </div>

            <div class="col-6 mb-3">
                <label for="surname" class="form-label"> Surname </label>
                <input type="text" name="surname" class="form-control" id="surname" required>
            </div>

            <div class="col-6 mb-3">
                <label for="address" class="form-label"> Address </label>
                <input type="text" name="address" class="form-control" id="address" required>
            </div>

            <div class="col-6 mb-3">
                <label for="telephone" class="form-label"> Telephone </label>
                <input type="tel" name="telephone" class="form-control" id="telephone" required>
            </div>
        </div>

        <div class="mb-3">
            <label for="email" class="form-label"> Email </label>
            <input type="email" name="email" class="form-control" id="email" required>
        </div>

        <div class="row">
            <div class="col-6 mb-3">
                <label for="password" class="form-label"> Password </label>
                <input type="password" name="password" class="form-control" id="password" required>
            </div>
            <div class="col-6 mb-3">
                <label for="repeat_password" class="form-label"> Repeat password </label>
                <input type="password" name="repeat_password" class="form-control" id="repeat_password" required>
            </div>
        </div>

        <div class="text-center mt-3">
            <button type="submit" name="submit_register" class="btn btn-primary"> Register </button>
        </div>
    </form>

    <p class="text-center mt-3">
        Already have an account? Login <a href="user/login">here</a>.
    </p>
</div>




