<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Order list
    </span>
</h3>

<table class="table">
    <thead>
        <tr>
            <th> Id </th>
            <th> Product </th>
            <th> Name </th>
            <th> Surname </th>
            <th> Address </th>
            <th> Price </th>
            <th> Status </th>
            <th> Date </th>

        </tr>
    </thead>
    <tbody>
        <?php foreach ($orders as $order): ?>
            <tr>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
