<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Add new product form
    </span>
</h3>

<div class="m-auto" style="width: 30%;" >
    <form action="/product/createSubmit" method="POST">
        <div class="mb-3">
            <label for="name" class="form-label"> Name </label>
            <input type="text" class="form-control" id="name" required>
        </div>

        <div class="mb-3">
            <label for="description" class="form-label"> Description </label>
            <input type="text" class="form-control" id="description" required>
        </div>

        <div class="mb-3">
            <label for="price" class="form-label"> Price [kn] </label>
            <input type="number" class="form-control" id="price" min="1" required>
        </div>

        <select class="form-select" required>
            <?php foreach ($productTypes as $productType): ?>
                <option value="<?= $productType['name'] ?>>">
                    <?= $productType['name'] ?>
                </option>
            <?php endforeach; ?>
        </select>

        <div class="text-center mt-3">
            <button type="submit" name="submit_product" class="btn btn-success">
                Add product
            </button>
        </div>
    </form>
</div>