<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Product list
    </span>
</h3>

<a href="create" class="btn btn-success">
    Add new product
</a>

<table class="table">
    <thead>
        <tr>
            <th> Id </th>
            <th> Image </th>
            <th> Name </th>
            <th> Description </th>
            <th> Price </th>
            <th> Type </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($products as $product): ?>
            <tr>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
                <td>  </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

