<h3 class="text-center mt-2">
    <span class="bg-light p-2">
        Product list
    </span>
</h3>

<a href="create" class="btn btn-success">
    Add new product
</a>

<table class="table">
    <thead>
        <tr>
            <th> Id </th>
            <th> Image </th>
            <th> Name </th>
            <th> Description </th>
            <th> Price [kn] </th>
            <th> Type </th>
            <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($products as $product): ?>
            <tr>
                <td> <?= $product['id'] ?> </td>
                <td>
                    <?php if(is_null($product['image_path'])): ?>
                        -
                    <?php else: ?>
                        <?= $product['image_path'] ?>
                    <?php endif; ?>
                </td>
                <td> <?= $product['name'] ?> </td>
                <td> <?= $product['description'] ?> </td>
                <td> <?= $product['price'] ?> </td>
                <td> <?= $product['type'] ?> </td>
                <td>
                    <a href="/product/edit?id=<?= $product['id'] ?>" class="btn btn-warning"> Edit </a>
                    <!-- Button trigger modal -->
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Delete
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    Are you sure that you want to delete this product?
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="/product/delete?id=<?= $product['id'] ?>" class="btn btn-danger"> Delete </a>
            </div>
        </div>
    </div>
</div>

