<div class="content">
	<div class="container-fluid">		
		<div class='row'>		
		<?php include('Pizza.php'); ?> 
		</div>
		<div class='row'>		
		<?php
		if(!empty($_SESSION["cart"])){
		?>      
			<div class="breadcrumb-section breadcrumb-bg">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 offset-lg-2 text-center">
					<div class="breadcrumb-text">
						<p>NARUDŽBA</p>
						<h1>KOŠARICA</h1>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- end breadcrumb section -->

	<!-- cart -->
	<div class="cart-section mt-150 mb-150">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-12">
					<div class="cart-table-wrap">
						<table class="cart-table">
							<thead class="cart-table-head">
								<tr class="table-head-row">
									<th class="product-remove"></th>		
                                    <th class="product-name">NAZIV</th>
									<th class="product-price">CIJENA</th>
									<th class="product-quantity">KOLIČINA</th>
									<th class="product-total">UKUPNO</th>
								</tr>
							</thead>
							<tbody>
								<tr class="table-body-row">
									<td class="product-remove"><a href="#"><i class="far fa-window-close"></i></a></td>
									<td class="product-name">Strawberry</td>
									<td class="product-price">$85</td>
									<td class="product-quantity"></td>
									<td class="product-total">1</td>
								</tr>
								</tbody>
						</table>
					</div>
				</div>

				<div class="col-lg-4">
					<div class="total-section">
						<table class="total-table">
							<thead class="total-table-head">
								<tr class="table-total-row">
									<th>UKUPNO</th>
									<th>CIJENA</th>
								</tr>
							</thead>
							<tbody>
															
								<tr class="total-data">
									<td><strong>UKUPNO: </strong></td>
									<td>$545</td>
								</tr>
							</tbody>
						</table>
						<div class="cart-buttons">
							<a href="<?=App::config('url')?>index" class="boxed-btn">NADOPUNI KOŠARICU</a>
							<a href="<?=App::config('url')?>potvrda/index" class="boxed-btn black">POTVRDI NARUDŽBU</a>
						</div>
					</div>

					
				</div>
			</div>
		</div>
	</div>
			
		<?php
		} elseif(empty($_SESSION["cart"])){
		?>
			<div class="container">
			<div class="jumbotron">
			<h3>Kad si gladan ,nisi svoj!</h3>
            <h3>Požuri , <a href="<?=App::config('url')?>">POGLEDAJ</a> i naruči .</h3>        
			</div>      
			</div>    
		<?php
		}
		?>		
		</div>		   
	</div> 	
</div>